✨ Add support for Course Settings
gradebook/server pull request #152
Opened 2020-12-07 03:55 UTC by vikaspotluri123

2020-12-11 05:54 UTC, joshcosta requested changes

2020-12-11 05:54 UTC, joshcosta commented on lib/database/schema.js
> +		settings: {type: 'text', nullable: true, subType: 'json', fallback: '{}', validations: {maxLength: 10000}}
1. If I'm understanding right how this was typed I think this should be `type: json` with no `subtype`

2. If the migration will yield `{}` as the "empty" value and we want valid json can we disallow null values?

2020-12-11 05:54 UTC, joshcosta commented on lib/services/validation/course-settings.js
> +		isValid: alias => typeof alias === 'string' && alias.length >= 0 && alias.length <= 15
```suggestion
		isValid: alias => typeof alias === 'string' && alias.length >= 0 && alias.length <= 20
```

`engineering ethics` is 18 characters and seems like a reasonable name length

2020-12-11 05:54 UTC, joshcosta commented on lib/services/validation/course-settings.js
> +	render_mode: { // eslint-disable-line camelcase
After thinking about it can we just use `grade_mode` for consistency with client? It doesn't seem worth changing the name

2020-12-11 05:54 UTC, joshcosta commented on lib/database/schema.js
> +		settings: {type: 'text', nullable: true, subType: 'json', fallback: '{}', validations: {maxLength: 10000}}
We also might consider updating the user settings schema to match

2020-12-21 03:07 UTC, vikaspotluri123 commented on lib/services/validation/course-settings.js
> +		isValid: alias => typeof alias === 'string' && alias.length >= 0 && alias.length <= 15
I chose 15 because that's what seems to fit best in the limited space of the bottom navigation. Thoughts?

2020-12-21 03:13 UTC, vikaspotluri123 commented on lib/database/schema.js
> +		settings: {type: 'text', nullable: true, subType: 'json', fallback: '{}', validations: {maxLength: 10000}}
You're right, good catch! Turns out type checking wasn't enabled for this file 👀

2020-12-30 21:09 UTC, joshcosta commented on lib/services/validation/course-settings.js
> +		isValid: alias => typeof alias === 'string' && alias.length >= 0 && alias.length <= 15
Given the potential new tab design with the full name underneath the class code I think we can be a little more lenient

2020-12-30 21:19 UTC, vikaspotluri123 commented on lib/services/validation/course-settings.js
> +		isValid: alias => typeof alias === 'string' && alias.length >= 0 && alias.length <= 15
We can have a more lenient length here and a stricter length in the client 👍🏾 I don't foresee us implementing a new design any time soon, but we can discuss that at our next meeting

2020-12-30 21:22 UTC, joshcosta approved these changes
Looks good 🚀

2020-12-30 21:23 UTC, merged