Dynamically render webmanifest file
gradebook/server pull request #158
Opened 2021-01-17 03:53 UTC by ramsays

The goal of this PR is to define a server rendered endpoint for the web app manifest file. The PR currently includes:

- Server-side rendering of `manifest.webmanifest` (icons are included in client PR)
  - Includes small icon for desktop browsers (Edge, Chrome)
  - Includes webp icons for Android (regular and maskable)
- Redirect for `favicon.ico` so legacy browsers have an icon (not referenced in `index.html`)

Left to do:

- [ ] Determine how to render web manifest (runtime/build time)
- [ ] Customize manifest theme color/icons for each school
- [ ] Determine if we want to use PWA shortcuts (probably not, school dependent)

Preliminary review and cold-eyes appreciated. Testing should be done with `manifest` branch in client.

2021-01-18 07:03 UTC, vikaspotluri123 requested changes
Good start 😄 

As an aside, the client submodule should only be updated for releases. The submodule tag is used to track what client release is guaranteed to work with a given server release

2021-01-18 07:03 UTC, vikaspotluri123 commented on lib/frontend/views/manifest.js
> +	return template.replace(/__THEME_COLOR__/g, color);
Since this is a more popular view, I'd prefer to use string interpolation over replacements (`${var}` vs `string.replace(/__VAR__/g, var)`)

2021-01-18 07:03 UTC, vikaspotluri123 commented on lib/services/school-config.js
> +	getRawSchoolConfig(hostname) {
This should be an internal method, and we should expose a method for getting the primary color

2021-01-18 07:03 UTC, vikaspotluri123 commented on lib/web/app.js
> +	app.get('/manifest.webmanifest', pwa.getManifest);
```suggestion
	app.get('/api/v0/web-manifest', pwa.getManifest);
```

You might also have to set `content-type` headers

2021-01-20 14:24 UTC, ramsays commented on lib/controllers/index.js
> +	pwa: require('./pwa'),
No longer needed 😁

2021-01-20 14:24 UTC, ramsays commented on lib/services/school-config.js
> +	getRawSchoolConfig(hostname) {
No longer needed 😁

2021-01-20 14:25 UTC, ramsays commented on lib/web/app.js
> +	app.get('/manifest.webmanifest', pwa.getManifest);
No longer needed 😁

2021-01-20 14:37 UTC, ramsays commented on lib/frontend/views/manifest.js
> +	return template.replace(/__THEME_COLOR__/g, color);
No longer needed! 👍

2021-01-20 14:39 UTC, ramsays commented
Because school config is now doing all the heavy lifting, server scope went from interesting to basically trivial. LGTM!

2021-01-20 16:21 UTC, vikaspotluri123 commented
Do we want to move the dynamically computed theme colors here as well? Now that we actually have a decent chunk of markup being dynamically rendered?

2021-01-20 16:43 UTC, vikaspotluri123 commented
Just to make sure we have the same expectations for client, I'll review this once client is ready. For now it looks good

2021-01-20 17:59 UTC, vikaspotluri123 commented on lib/utils/browser-injects.js
> +};
This should be renamed to `apple-meta-tax.js` (or `apple-meta.js`) and needs tests using UAs from iOS, iPadOS, Safari, Edge, ChrEdge, Chrome, Firefox, and Brave (along with any others you can think of)

```suggestion
// @ts-check
const CDN_ROOT = 'https://static.gradebook.app/sYbR9JXKTI/';
const APPLE_SPECIFIC_META_TAGS = `
<meta name="apple-touch-fullscreen" content="yes" />
<meta name="apple-mobile-web-app-title" content="Gradebook" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="default" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}apple-splash-iphone.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-iphone-plus.png" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-iphone-x.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-iphone-xr.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-iphone-max.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-iphone-12.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-iphone-12max.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-sm.png" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-sm-horiz.png" media="(device-width: 1024px) and (device-height: 768px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-md.png" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-md-horiz.png" media="(device-width: 1080px) and (device-height: 810px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-lg.png" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-lg-horiz.png" media="(device-width: 1112px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-xl.png" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-xl-horiz.png" media="(device-width: 1194px) and (device-height: 834px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-2xl.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" />
<link rel="apple-touch-startup-image" href="${CDN_ROOT}/apple-splash-ipad-2xl-horiz.png" media="(device-width: 1366px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" />
`;

/**
* @param {Gradebook.Request} request
*/
module.exports = request => {
	const ua = request.headers['user-agent'];
	const hasSafari = ua.includes('Safari');
	const hasChrome = ua.includes('Chrom');
	const hasEdge = ua.includes('Edg');

	return (hasSafari && !hasChrome && !hasEdge) ? APPLE_SPECIFIC_META_TAGS : '';
};

```

2021-01-20 19:17 UTC, ramsays commented
A few comments on the user agent tests:

- Brave (and other smaller browsers) copy Chromes user agent string
- I didn't include MSEdge because it is being quickly superseded by the new Edge
- iPad and Mac now use the same user agent string (as of iOS 13+), so only one test is available, even though we would desire to not render the apple tags on Safari desktop

2021-01-21 16:12 UTC, joshcosta commented on lib/utils/apple-meta.js
> +	return (hasSafari && !hasChrome && !hasEdge) ? APPLE_SPECIFIC_META_TAGS : '';
Do we need to check for Chrome and Edge here?

2021-01-21 16:13 UTC, vikaspotluri123 commented on lib/utils/apple-meta.js
> +	return (hasSafari && !hasChrome && !hasEdge) ? APPLE_SPECIFIC_META_TAGS : '';
Based on the current algorithm, yes, because Chrome includes Safari in their UA.

My preferred algo is matching `/iphone|ipod|mac/i`

2021-01-21 16:16 UTC, joshcosta commented
Before release we need to make sure the assets are up on static.

2021-01-21 16:45 UTC, ramsays commented on lib/utils/apple-meta.js
> +	return (hasSafari && !hasChrome && !hasEdge) ? APPLE_SPECIFIC_META_TAGS : '';
I checked that and yeah the regex should work.

2021-01-21 16:46 UTC, ramsays commented on test/unit/utils/apple-meta.spec.js
> +		expect(appleMeta(requestStub(safariPhoneUA)).length).to.not.be.equal(0);
Indeed 👍

2021-01-21 16:49 UTC, vikaspotluri123 approved these changes

2021-01-22 05:10 UTC, merged