✨ add user issue reporting route
gradebook/server pull request #206
Opened 2022-05-21 22:32 UTC by vikaspotluri123

Validates and transforms data such that it can be processed and used by an internal service.
Includes timestamp-based request signing

2022-07-03 23:56 UTC, joshcosta requested changes

2022-07-03 23:56 UTC, joshcosta commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "maxLength": 10000
I don't think the server needs to enforce minimum lengths here

2022-07-03 23:56 UTC, joshcosta commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "type": "array",
Maybe a max length of the array?

2022-07-03 23:56 UTC, joshcosta commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
Let's log the id regardless of if the email is logged

2022-07-03 23:58 UTC, vikaspotluri123 commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "maxLength": 10000
Validation happens at the server level (not the worker level)

2022-07-04 00:20 UTC, vikaspotluri123 commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "type": "array",
Categories need additional validation (explicit allow list) but we need to come up with the list first

2022-07-04 00:27 UTC, vikaspotluri123 commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
What's the use case for tracking it?

2022-07-04 00:29 UTC, joshcosta commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "maxLength": 10000
In other words I'm saying I think the minimums would be fine at 0. There would be less dependence between server and client on keeping the minimums in step, and then client can be stricter if we want to enforce minimums

2022-07-04 00:31 UTC, joshcosta commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
Junk email provided. Would be the same as not allowing contacting, and if we are storing the id in that case I think it makes sense in this case as well

2022-07-04 00:54 UTC, vikaspotluri123 commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
The email comes from the Google user, not from client input

2022-07-04 01:02 UTC, vikaspotluri123 commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "maxLength": 10000
_If_ there's debug data, it has to be at least 50 chars. Debug data is not required. With the sentry data (breadcrumbs and time stamps) it will easily meet that requirement.

I can see a reason to not want this validation but that's the reasoning for having a minimum

2022-07-04 03:35 UTC, joshcosta commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
Ok got it. Still think there is no harm in always including the id

2022-07-04 06:32 UTC, vikaspotluri123 commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
To be honest, I'd rather not even include the user id for absolute privacy, but we don't really have a choice in that regard since we need to be able to reproduce the report, which might require cloning the user's semester (e.g. if they report an issue with GPA insights). For a user that included their email, we either work with them to get everything set up, or we grab the user's id in the event it's needed.

2022-08-09 06:05 UTC, joshcosta commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "maxLength": 10000
I still think that is unnecessary but I won't hold out approval over it

2022-08-09 06:09 UTC, joshcosta commented on lib/controllers/user.js
> +			proxyPayload.identifier = request.user.id;
Ok that's fine

2022-08-09 06:09 UTC, joshcosta approved these changes

2022-08-09 16:08 UTC, vikaspotluri123 commented on lib/services/validation/schemas/user-issue-reporter.json
> +      "maxLength": 10000
I'll leave it for now in case there's something I was thinking of that I can't remember now, and if it ends up biting us, we can always remove it 🙃

2022-08-20 21:05 UTC, ramsays approved these changes
Looks good, Josh already asked the questions I had tbh

2022-08-20 21:05 UTC, ramsays commented on config.example.json
> +      "lifetime": 604800
Reason for 15? Don't know if you had a thought process or if it's just arbitrary.

2022-08-21 02:06 UTC, vikaspotluri123 commented on config.example.json
> +      "lifetime": 604800
Pretty arbitrary 😄 Based on the lessons learned with other ratelimits, wanted to do something that's unlikely to be hit, but also won't be an avenue for spam

2022-08-21 02:08 UTC, vikaspotluri123 commented
Gonna go ahead and merge since this is the groundwork for more features in the future. Let's still get the conversations resolved though!

2022-08-21 02:08 UTC, merged